### ISSUE TITLE
 Installation Lab

### ISSUE THREAD

**Issue by RonVander** [RonVander/SEBC#1]

**Comment by cfusi** [comment]
Please make sure that the settings survive after a reboot.
Specifically for transparent hugepages see here:
https://www.cloudera.com/documentation/enterprise/5-9-x/topics/cdh_admin_performance.html

For swappiness, you need to add the line:
`vm.swappiness=1`
to the file:
`/etc/sysctl.conf`

Also make sure that the services mtpd and nscd start at boot:
`systemctl enable <service>`

Please give evidence of the mysql replica, if set up

The installed CDH version is the latest one (5.14.0).
Your platform (16.04 LTS (Xenial)) is supported starting from 5.11 on, see here:
https://www.cloudera.com/documentation/enterprise/release-notes/topics/rn_consolidated_pcm.html#concept_dcw_m5v_jz

**Comment by cfusi** [comment]
It seems that mysql replication is not working

**Comment by RonVander** [comment]
Understood, I know what went wrong and going to fix it after the other labs are done.

**Comment by cfusi** [comment]
Lab is complete. We reviewed what to takes to have the replication fixed
